// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (org_id, actor_id, action, target_type, target_id, metadata, ip_address)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, org_id, actor_id, action, target_type, target_id, metadata, ip_address, created_at
`

type CreateAuditLogParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	ActorID    pgtype.UUID `json:"actor_id"`
	Action     string      `json:"action"`
	TargetType pgtype.Text `json:"target_type"`
	TargetID   pgtype.UUID `json:"target_id"`
	Metadata   []byte      `json:"metadata"`
	IpAddress  pgtype.Text `json:"ip_address"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.OrgID,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Metadata,
		arg.IpAddress,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ActorID,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Metadata,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, org_id, actor_id, action, target_type, target_id, metadata, ip_address, created_at
FROM audit_logs
WHERE ($1::uuid IS NULL OR org_id = $1)
ORDER BY created_at DESC
LIMIT $2
`

type ListAuditLogsParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ActorID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Metadata,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
