// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRecentOTPRequests = `-- name: CountRecentOTPRequests :one
SELECT COUNT(*) FROM otp_codes
WHERE user_id = $1 AND purpose = $2 AND created_at > NOW() - interval '1 hour'
`

type CountRecentOTPRequestsParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Purpose OtpPurpose  `json:"purpose"`
}

func (q *Queries) CountRecentOTPRequests(ctx context.Context, arg CountRecentOTPRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentOTPRequests, arg.UserID, arg.Purpose)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOTP = `-- name: CreateOTP :one
INSERT INTO otp_codes (user_id, code, channel, purpose, expires_at)
VALUES ($1, $2, $3, $4, NOW() + interval '5 minutes')
RETURNING id, user_id, code, channel, purpose, attempts, expires_at, verified_at, created_at
`

type CreateOTPParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Code    string      `json:"code"`
	Channel OtpChannel  `json:"channel"`
	Purpose OtpPurpose  `json:"purpose"`
}

func (q *Queries) CreateOTP(ctx context.Context, arg CreateOTPParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, createOTP,
		arg.UserID,
		arg.Code,
		arg.Channel,
		arg.Purpose,
	)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.Channel,
		&i.Purpose,
		&i.Attempts,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, phone, password_hash, role, org_id, language_pref, invited_by, must_change_password)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, org_id, name, display_name, email, phone, password_hash, avatar_url, role, language_pref, is_active, invited_by, must_change_password, last_login_at, created_at
`

type CreateUserParams struct {
	Name               string      `json:"name"`
	Email              pgtype.Text `json:"email"`
	Phone              pgtype.Text `json:"phone"`
	PasswordHash       pgtype.Text `json:"password_hash"`
	Role               UserRole    `json:"role"`
	OrgID              pgtype.UUID `json:"org_id"`
	LanguagePref       string      `json:"language_pref"`
	InvitedBy          pgtype.UUID `json:"invited_by"`
	MustChangePassword bool        `json:"must_change_password"`
}

type CreateUserRow struct {
	ID                 pgtype.UUID        `json:"id"`
	OrgID              pgtype.UUID        `json:"org_id"`
	Name               string             `json:"name"`
	DisplayName        pgtype.Text        `json:"display_name"`
	Email              pgtype.Text        `json:"email"`
	Phone              pgtype.Text        `json:"phone"`
	PasswordHash       pgtype.Text        `json:"password_hash"`
	AvatarUrl          pgtype.Text        `json:"avatar_url"`
	Role               UserRole           `json:"role"`
	LanguagePref       string             `json:"language_pref"`
	IsActive           bool               `json:"is_active"`
	InvitedBy          pgtype.UUID        `json:"invited_by"`
	MustChangePassword bool               `json:"must_change_password"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.Role,
		arg.OrgID,
		arg.LanguagePref,
		arg.InvitedBy,
		arg.MustChangePassword,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.Role,
		&i.LanguagePref,
		&i.IsActive,
		&i.InvitedBy,
		&i.MustChangePassword,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestValidOTP = `-- name: GetLatestValidOTP :one
SELECT id, user_id, code, channel, purpose, attempts, expires_at, verified_at, created_at
FROM otp_codes
WHERE user_id = $1 AND channel = $2 AND purpose = $3 AND verified_at IS NULL AND expires_at > NOW()
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestValidOTPParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Channel OtpChannel  `json:"channel"`
	Purpose OtpPurpose  `json:"purpose"`
}

func (q *Queries) GetLatestValidOTP(ctx context.Context, arg GetLatestValidOTPParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, getLatestValidOTP, arg.UserID, arg.Channel, arg.Purpose)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.Channel,
		&i.Purpose,
		&i.Attempts,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserAuthByContact = `-- name: GetUserAuthByContact :one
SELECT id, org_id, name, display_name, email, phone, password_hash, avatar_url, role, language_pref, is_active, invited_by, must_change_password, last_login_at, created_at
FROM users
WHERE email = $1 OR phone = $1
ORDER BY (email = $1) DESC
LIMIT 1
`

type GetUserAuthByContactRow struct {
	ID                 pgtype.UUID        `json:"id"`
	OrgID              pgtype.UUID        `json:"org_id"`
	Name               string             `json:"name"`
	DisplayName        pgtype.Text        `json:"display_name"`
	Email              pgtype.Text        `json:"email"`
	Phone              pgtype.Text        `json:"phone"`
	PasswordHash       pgtype.Text        `json:"password_hash"`
	AvatarUrl          pgtype.Text        `json:"avatar_url"`
	Role               UserRole           `json:"role"`
	LanguagePref       string             `json:"language_pref"`
	IsActive           bool               `json:"is_active"`
	InvitedBy          pgtype.UUID        `json:"invited_by"`
	MustChangePassword bool               `json:"must_change_password"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserAuthByContact(ctx context.Context, email pgtype.Text) (GetUserAuthByContactRow, error) {
	row := q.db.QueryRow(ctx, getUserAuthByContact, email)
	var i GetUserAuthByContactRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.Role,
		&i.LanguagePref,
		&i.IsActive,
		&i.InvitedBy,
		&i.MustChangePassword,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserAuthByEmail = `-- name: GetUserAuthByEmail :one
SELECT id, org_id, name, display_name, email, phone, password_hash, avatar_url, role, language_pref, is_active, invited_by, must_change_password, last_login_at, created_at
FROM users
WHERE email = $1
LIMIT 1
`

type GetUserAuthByEmailRow struct {
	ID                 pgtype.UUID        `json:"id"`
	OrgID              pgtype.UUID        `json:"org_id"`
	Name               string             `json:"name"`
	DisplayName        pgtype.Text        `json:"display_name"`
	Email              pgtype.Text        `json:"email"`
	Phone              pgtype.Text        `json:"phone"`
	PasswordHash       pgtype.Text        `json:"password_hash"`
	AvatarUrl          pgtype.Text        `json:"avatar_url"`
	Role               UserRole           `json:"role"`
	LanguagePref       string             `json:"language_pref"`
	IsActive           bool               `json:"is_active"`
	InvitedBy          pgtype.UUID        `json:"invited_by"`
	MustChangePassword bool               `json:"must_change_password"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserAuthByEmail(ctx context.Context, email pgtype.Text) (GetUserAuthByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserAuthByEmail, email)
	var i GetUserAuthByEmailRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.Role,
		&i.LanguagePref,
		&i.IsActive,
		&i.InvitedBy,
		&i.MustChangePassword,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserAuthByID = `-- name: GetUserAuthByID :one
SELECT id, org_id, name, display_name, email, phone, password_hash, avatar_url, role, language_pref, is_active, invited_by, must_change_password, last_login_at, created_at
FROM users
WHERE id = $1
LIMIT 1
`

type GetUserAuthByIDRow struct {
	ID                 pgtype.UUID        `json:"id"`
	OrgID              pgtype.UUID        `json:"org_id"`
	Name               string             `json:"name"`
	DisplayName        pgtype.Text        `json:"display_name"`
	Email              pgtype.Text        `json:"email"`
	Phone              pgtype.Text        `json:"phone"`
	PasswordHash       pgtype.Text        `json:"password_hash"`
	AvatarUrl          pgtype.Text        `json:"avatar_url"`
	Role               UserRole           `json:"role"`
	LanguagePref       string             `json:"language_pref"`
	IsActive           bool               `json:"is_active"`
	InvitedBy          pgtype.UUID        `json:"invited_by"`
	MustChangePassword bool               `json:"must_change_password"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserAuthByID(ctx context.Context, id pgtype.UUID) (GetUserAuthByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserAuthByID, id)
	var i GetUserAuthByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.Role,
		&i.LanguagePref,
		&i.IsActive,
		&i.InvitedBy,
		&i.MustChangePassword,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserAuthByPhone = `-- name: GetUserAuthByPhone :one
SELECT id, org_id, name, display_name, email, phone, password_hash, avatar_url, role, language_pref, is_active, invited_by, must_change_password, last_login_at, created_at
FROM users
WHERE phone = $1
LIMIT 1
`

type GetUserAuthByPhoneRow struct {
	ID                 pgtype.UUID        `json:"id"`
	OrgID              pgtype.UUID        `json:"org_id"`
	Name               string             `json:"name"`
	DisplayName        pgtype.Text        `json:"display_name"`
	Email              pgtype.Text        `json:"email"`
	Phone              pgtype.Text        `json:"phone"`
	PasswordHash       pgtype.Text        `json:"password_hash"`
	AvatarUrl          pgtype.Text        `json:"avatar_url"`
	Role               UserRole           `json:"role"`
	LanguagePref       string             `json:"language_pref"`
	IsActive           bool               `json:"is_active"`
	InvitedBy          pgtype.UUID        `json:"invited_by"`
	MustChangePassword bool               `json:"must_change_password"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserAuthByPhone(ctx context.Context, phone pgtype.Text) (GetUserAuthByPhoneRow, error) {
	row := q.db.QueryRow(ctx, getUserAuthByPhone, phone)
	var i GetUserAuthByPhoneRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.Role,
		&i.LanguagePref,
		&i.IsActive,
		&i.InvitedBy,
		&i.MustChangePassword,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementOTPAttempts = `-- name: IncrementOTPAttempts :exec
UPDATE otp_codes SET attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) IncrementOTPAttempts(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementOTPAttempts, id)
	return err
}

const isEmailTaken = `-- name: IsEmailTaken :one
SELECT EXISTS (SELECT 1 FROM users WHERE email = $1)
`

func (q *Queries) IsEmailTaken(ctx context.Context, email pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, isEmailTaken, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isPhoneTaken = `-- name: IsPhoneTaken :one
SELECT EXISTS (SELECT 1 FROM users WHERE phone = $1)
`

func (q *Queries) IsPhoneTaken(ctx context.Context, phone pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, isPhoneTaken, phone)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const markOTPVerified = `-- name: MarkOTPVerified :exec
UPDATE otp_codes SET verified_at = NOW() WHERE id = $1 AND verified_at IS NULL
`

func (q *Queries) MarkOTPVerified(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOTPVerified, id)
	return err
}

const updateLanguagePref = `-- name: UpdateLanguagePref :exec
UPDATE users SET language_pref = $2 WHERE id = $1
`

type UpdateLanguagePrefParams struct {
	ID           pgtype.UUID `json:"id"`
	LanguagePref string      `json:"language_pref"`
}

func (q *Queries) UpdateLanguagePref(ctx context.Context, arg UpdateLanguagePrefParams) error {
	_, err := q.db.Exec(ctx, updateLanguagePref, arg.ID, arg.LanguagePref)
	return err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users SET last_login_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateLastLogin, id)
	return err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE users SET password_hash = $2, must_change_password = FALSE WHERE id = $1
`

type UpdatePasswordHashParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const updatePasswordRequireReset = `-- name: UpdatePasswordRequireReset :exec
UPDATE users SET password_hash = $2, must_change_password = TRUE WHERE id = $1
`

type UpdatePasswordRequireResetParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) UpdatePasswordRequireReset(ctx context.Context, arg UpdatePasswordRequireResetParams) error {
	_, err := q.db.Exec(ctx, updatePasswordRequireReset, arg.ID, arg.PasswordHash)
	return err
}
