// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRecentOTPRequests = `-- name: CountRecentOTPRequests :one
SELECT COUNT(*) FROM otp_codes
WHERE user_id = $1 AND created_at > NOW() - interval '1 hour'
`

func (q *Queries) CountRecentOTPRequests(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentOTPRequests, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOTP = `-- name: CreateOTP :one
INSERT INTO otp_codes (user_id, code, channel, expires_at)
VALUES ($1, $2, $3, NOW() + interval '5 minutes')
RETURNING id, user_id, code, channel, expires_at, verified_at, created_at
`

type CreateOTPParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Code    string      `json:"code"`
	Channel OtpChannel  `json:"channel"`
}

func (q *Queries) CreateOTP(ctx context.Context, arg CreateOTPParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, createOTP, arg.UserID, arg.Code, arg.Channel)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.Channel,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, phone, password_hash, role, language_pref)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, email, phone, role, language_pref, created_at
`

type CreateUserParams struct {
	Name         string      `json:"name"`
	Email        pgtype.Text `json:"email"`
	Phone        pgtype.Text `json:"phone"`
	PasswordHash pgtype.Text `json:"password_hash"`
	Role         UserRole    `json:"role"`
	LanguagePref string      `json:"language_pref"`
}

type CreateUserRow struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Email        pgtype.Text        `json:"email"`
	Phone        pgtype.Text        `json:"phone"`
	Role         UserRole           `json:"role"`
	LanguagePref string             `json:"language_pref"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.Role,
		arg.LanguagePref,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.LanguagePref,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestValidOTP = `-- name: GetLatestValidOTP :one
SELECT id, user_id, code, channel, expires_at, verified_at
FROM otp_codes
WHERE user_id = $1 AND channel = $2 AND verified_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestValidOTPParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Channel OtpChannel  `json:"channel"`
}

type GetLatestValidOTPRow struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Code       string             `json:"code"`
	Channel    OtpChannel         `json:"channel"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
}

func (q *Queries) GetLatestValidOTP(ctx context.Context, arg GetLatestValidOTPParams) (GetLatestValidOTPRow, error) {
	row := q.db.QueryRow(ctx, getLatestValidOTP, arg.UserID, arg.Channel)
	var i GetLatestValidOTPRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.Channel,
		&i.ExpiresAt,
		&i.VerifiedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, phone, role, language_pref, created_at
FROM users
WHERE email = $1 LIMIT 1
`

type GetUserByEmailRow struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Email        pgtype.Text        `json:"email"`
	Phone        pgtype.Text        `json:"phone"`
	Role         UserRole           `json:"role"`
	LanguagePref string             `json:"language_pref"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.LanguagePref,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, phone, role, language_pref, created_at
FROM users
WHERE id = $1 LIMIT 1
`

type GetUserByIDRow struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Email        pgtype.Text        `json:"email"`
	Phone        pgtype.Text        `json:"phone"`
	Role         UserRole           `json:"role"`
	LanguagePref string             `json:"language_pref"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.LanguagePref,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, name, email, phone, role, language_pref, created_at
FROM users
WHERE phone = $1 LIMIT 1
`

type GetUserByPhoneRow struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Email        pgtype.Text        `json:"email"`
	Phone        pgtype.Text        `json:"phone"`
	Role         UserRole           `json:"role"`
	LanguagePref string             `json:"language_pref"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserByPhone(ctx context.Context, phone pgtype.Text) (GetUserByPhoneRow, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i GetUserByPhoneRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.LanguagePref,
		&i.CreatedAt,
	)
	return i, err
}

const markOTPVerified = `-- name: MarkOTPVerified :exec
UPDATE otp_codes SET verified_at = NOW() WHERE id = $1 AND verified_at IS NULL
`

func (q *Queries) MarkOTPVerified(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOTPVerified, id)
	return err
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, name, email, phone, role, language_pref, created_at
FROM users
WHERE name_search @@ plainto_tsquery('english', $1)
   OR name ILIKE '%' || $1 || '%'
ORDER BY created_at DESC
LIMIT $2
`

type SearchUsersParams struct {
	PlaintoTsquery string `json:"plainto_tsquery"`
	Limit          int32  `json:"limit"`
}

type SearchUsersRow struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Email        pgtype.Text        `json:"email"`
	Phone        pgtype.Text        `json:"phone"`
	Role         UserRole           `json:"role"`
	LanguagePref string             `json:"language_pref"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.PlaintoTsquery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersRow{}
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Role,
			&i.LanguagePref,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLanguagePref = `-- name: UpdateLanguagePref :exec
UPDATE users SET language_pref = $2 WHERE id = $1
`

type UpdateLanguagePrefParams struct {
	ID           pgtype.UUID `json:"id"`
	LanguagePref string      `json:"language_pref"`
}

func (q *Queries) UpdateLanguagePref(ctx context.Context, arg UpdateLanguagePrefParams) error {
	_, err := q.db.Exec(ctx, updateLanguagePref, arg.ID, arg.LanguagePref)
	return err
}
