// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearDocumentAccessList = `-- name: ClearDocumentAccessList :exec
DELETE FROM document_access WHERE document_id = $1
`

func (q *Queries) ClearDocumentAccessList(ctx context.Context, documentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearDocumentAccessList, documentID)
	return err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (uploaded_by, group_id, filename, storage_path, visibility, password_hash, allowed_roles)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, uploaded_by, group_id, filename, storage_path, visibility, password_hash, allowed_roles, created_at
`

type CreateDocumentParams struct {
	UploadedBy   pgtype.UUID `json:"uploaded_by"`
	GroupID      pgtype.UUID `json:"group_id"`
	Filename     string      `json:"filename"`
	StoragePath  string      `json:"storage_path"`
	Visibility   string      `json:"visibility"`
	PasswordHash pgtype.Text `json:"password_hash"`
	AllowedRoles []string    `json:"allowed_roles"`
}

type CreateDocumentRow struct {
	ID           pgtype.UUID        `json:"id"`
	UploadedBy   pgtype.UUID        `json:"uploaded_by"`
	GroupID      pgtype.UUID        `json:"group_id"`
	Filename     string             `json:"filename"`
	StoragePath  string             `json:"storage_path"`
	Visibility   string             `json:"visibility"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	AllowedRoles []string           `json:"allowed_roles"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (CreateDocumentRow, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.UploadedBy,
		arg.GroupID,
		arg.Filename,
		arg.StoragePath,
		arg.Visibility,
		arg.PasswordHash,
		arg.AllowedRoles,
	)
	var i CreateDocumentRow
	err := row.Scan(
		&i.ID,
		&i.UploadedBy,
		&i.GroupID,
		&i.Filename,
		&i.StoragePath,
		&i.Visibility,
		&i.PasswordHash,
		&i.AllowedRoles,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDocument, id)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT id, uploaded_by, group_id, filename, storage_path, visibility, password_hash, allowed_roles, created_at
FROM documents
WHERE id = $1 LIMIT 1
`

type GetDocumentRow struct {
	ID           pgtype.UUID        `json:"id"`
	UploadedBy   pgtype.UUID        `json:"uploaded_by"`
	GroupID      pgtype.UUID        `json:"group_id"`
	Filename     string             `json:"filename"`
	StoragePath  string             `json:"storage_path"`
	Visibility   string             `json:"visibility"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	AllowedRoles []string           `json:"allowed_roles"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetDocument(ctx context.Context, id pgtype.UUID) (GetDocumentRow, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i GetDocumentRow
	err := row.Scan(
		&i.ID,
		&i.UploadedBy,
		&i.GroupID,
		&i.Filename,
		&i.StoragePath,
		&i.Visibility,
		&i.PasswordHash,
		&i.AllowedRoles,
		&i.CreatedAt,
	)
	return i, err
}

const getDocumentAccessList = `-- name: GetDocumentAccessList :many
SELECT da.user_id, COALESCE(u.display_name, u.name) AS user_name, u.email
FROM document_access da
JOIN users u ON u.id = da.user_id
WHERE da.document_id = $1
`

type GetDocumentAccessListRow struct {
	UserID   pgtype.UUID `json:"user_id"`
	UserName string      `json:"user_name"`
	Email    pgtype.Text `json:"email"`
}

func (q *Queries) GetDocumentAccessList(ctx context.Context, documentID pgtype.UUID) ([]GetDocumentAccessListRow, error) {
	rows, err := q.db.Query(ctx, getDocumentAccessList, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDocumentAccessListRow{}
	for rows.Next() {
		var i GetDocumentAccessListRow
		if err := rows.Scan(&i.UserID, &i.UserName, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const grantDocumentAccess = `-- name: GrantDocumentAccess :exec
INSERT INTO document_access (document_id, user_id)
VALUES ($1, $2)
ON CONFLICT (document_id, user_id) DO NOTHING
`

type GrantDocumentAccessParams struct {
	DocumentID pgtype.UUID `json:"document_id"`
	UserID     pgtype.UUID `json:"user_id"`
}

func (q *Queries) GrantDocumentAccess(ctx context.Context, arg GrantDocumentAccessParams) error {
	_, err := q.db.Exec(ctx, grantDocumentAccess, arg.DocumentID, arg.UserID)
	return err
}

const listAllDocuments = `-- name: ListAllDocuments :many
SELECT d.id, d.uploaded_by, d.group_id, d.filename, d.storage_path,
       d.visibility, d.password_hash, d.allowed_roles, d.created_at,
       COALESCE(u.display_name, u.name) AS uploader_name
FROM documents d
JOIN users u ON u.id = d.uploaded_by
ORDER BY d.created_at DESC
`

type ListAllDocumentsRow struct {
	ID           pgtype.UUID        `json:"id"`
	UploadedBy   pgtype.UUID        `json:"uploaded_by"`
	GroupID      pgtype.UUID        `json:"group_id"`
	Filename     string             `json:"filename"`
	StoragePath  string             `json:"storage_path"`
	Visibility   string             `json:"visibility"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	AllowedRoles []string           `json:"allowed_roles"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UploaderName string             `json:"uploader_name"`
}

func (q *Queries) ListAllDocuments(ctx context.Context) ([]ListAllDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listAllDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllDocumentsRow{}
	for rows.Next() {
		var i ListAllDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UploadedBy,
			&i.GroupID,
			&i.Filename,
			&i.StoragePath,
			&i.Visibility,
			&i.PasswordHash,
			&i.AllowedRoles,
			&i.CreatedAt,
			&i.UploaderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeDocumentAccess = `-- name: RevokeDocumentAccess :exec
DELETE FROM document_access WHERE document_id = $1 AND user_id = $2
`

type RevokeDocumentAccessParams struct {
	DocumentID pgtype.UUID `json:"document_id"`
	UserID     pgtype.UUID `json:"user_id"`
}

func (q *Queries) RevokeDocumentAccess(ctx context.Context, arg RevokeDocumentAccessParams) error {
	_, err := q.db.Exec(ctx, revokeDocumentAccess, arg.DocumentID, arg.UserID)
	return err
}

const setDocumentPassword = `-- name: SetDocumentPassword :exec
UPDATE documents SET password_hash = $2 WHERE id = $1
`

type SetDocumentPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) SetDocumentPassword(ctx context.Context, arg SetDocumentPasswordParams) error {
	_, err := q.db.Exec(ctx, setDocumentPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateDocumentVisibility = `-- name: UpdateDocumentVisibility :one
UPDATE documents SET visibility = $2, allowed_roles = $3
WHERE id = $1
RETURNING id, uploaded_by, group_id, filename, storage_path, visibility, password_hash, allowed_roles, created_at
`

type UpdateDocumentVisibilityParams struct {
	ID           pgtype.UUID `json:"id"`
	Visibility   string      `json:"visibility"`
	AllowedRoles []string    `json:"allowed_roles"`
}

type UpdateDocumentVisibilityRow struct {
	ID           pgtype.UUID        `json:"id"`
	UploadedBy   pgtype.UUID        `json:"uploaded_by"`
	GroupID      pgtype.UUID        `json:"group_id"`
	Filename     string             `json:"filename"`
	StoragePath  string             `json:"storage_path"`
	Visibility   string             `json:"visibility"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	AllowedRoles []string           `json:"allowed_roles"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateDocumentVisibility(ctx context.Context, arg UpdateDocumentVisibilityParams) (UpdateDocumentVisibilityRow, error) {
	row := q.db.QueryRow(ctx, updateDocumentVisibility, arg.ID, arg.Visibility, arg.AllowedRoles)
	var i UpdateDocumentVisibilityRow
	err := row.Scan(
		&i.ID,
		&i.UploadedBy,
		&i.GroupID,
		&i.Filename,
		&i.StoragePath,
		&i.Visibility,
		&i.PasswordHash,
		&i.AllowedRoles,
		&i.CreatedAt,
	)
	return i, err
}
