// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (uploaded_by, group_id, filename, storage_path, visibility, password_hash)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, uploaded_by, group_id, filename, storage_path, visibility, password_hash, created_at
`

type CreateDocumentParams struct {
	UploadedBy   pgtype.UUID   `json:"uploaded_by"`
	GroupID      pgtype.UUID   `json:"group_id"`
	Filename     string        `json:"filename"`
	StoragePath  string        `json:"storage_path"`
	Visibility   DocVisibility `json:"visibility"`
	PasswordHash pgtype.Text   `json:"password_hash"`
}

type CreateDocumentRow struct {
	ID           pgtype.UUID        `json:"id"`
	UploadedBy   pgtype.UUID        `json:"uploaded_by"`
	GroupID      pgtype.UUID        `json:"group_id"`
	Filename     string             `json:"filename"`
	StoragePath  string             `json:"storage_path"`
	Visibility   DocVisibility      `json:"visibility"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (CreateDocumentRow, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.UploadedBy,
		arg.GroupID,
		arg.Filename,
		arg.StoragePath,
		arg.Visibility,
		arg.PasswordHash,
	)
	var i CreateDocumentRow
	err := row.Scan(
		&i.ID,
		&i.UploadedBy,
		&i.GroupID,
		&i.Filename,
		&i.StoragePath,
		&i.Visibility,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getDocument = `-- name: GetDocument :one
SELECT id, uploaded_by, group_id, filename, storage_path, visibility, password_hash, created_at
FROM documents
WHERE id = $1 LIMIT 1
`

type GetDocumentRow struct {
	ID           pgtype.UUID        `json:"id"`
	UploadedBy   pgtype.UUID        `json:"uploaded_by"`
	GroupID      pgtype.UUID        `json:"group_id"`
	Filename     string             `json:"filename"`
	StoragePath  string             `json:"storage_path"`
	Visibility   DocVisibility      `json:"visibility"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetDocument(ctx context.Context, id pgtype.UUID) (GetDocumentRow, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i GetDocumentRow
	err := row.Scan(
		&i.ID,
		&i.UploadedBy,
		&i.GroupID,
		&i.Filename,
		&i.StoragePath,
		&i.Visibility,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const grantDocumentAccess = `-- name: GrantDocumentAccess :exec
INSERT INTO document_access (document_id, user_id)
VALUES ($1, $2)
ON CONFLICT (document_id, user_id) DO NOTHING
`

type GrantDocumentAccessParams struct {
	DocumentID pgtype.UUID `json:"document_id"`
	UserID     pgtype.UUID `json:"user_id"`
}

func (q *Queries) GrantDocumentAccess(ctx context.Context, arg GrantDocumentAccessParams) error {
	_, err := q.db.Exec(ctx, grantDocumentAccess, arg.DocumentID, arg.UserID)
	return err
}

const hasDocumentAccess = `-- name: HasDocumentAccess :one
SELECT EXISTS (
    SELECT 1 FROM documents d
    WHERE d.id = $1
      AND (d.visibility = 'all' OR d.uploaded_by = $2)
    UNION
    SELECT 1 FROM document_access da
    WHERE da.document_id = $1 AND da.user_id = $2
) AS has_access
`

type HasDocumentAccessParams struct {
	ID         pgtype.UUID `json:"id"`
	UploadedBy pgtype.UUID `json:"uploaded_by"`
}

func (q *Queries) HasDocumentAccess(ctx context.Context, arg HasDocumentAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasDocumentAccess, arg.ID, arg.UploadedBy)
	var has_access bool
	err := row.Scan(&has_access)
	return has_access, err
}

const listDocumentsForUser = `-- name: ListDocumentsForUser :many
SELECT DISTINCT d.id, d.uploaded_by, d.group_id, d.filename, d.storage_path,
                d.visibility, d.password_hash, d.created_at
FROM documents d
LEFT JOIN document_access da ON da.document_id = d.id
WHERE d.visibility = 'all'
   OR d.uploaded_by = $1
   OR da.user_id = $1
ORDER BY d.created_at DESC
`

type ListDocumentsForUserRow struct {
	ID           pgtype.UUID        `json:"id"`
	UploadedBy   pgtype.UUID        `json:"uploaded_by"`
	GroupID      pgtype.UUID        `json:"group_id"`
	Filename     string             `json:"filename"`
	StoragePath  string             `json:"storage_path"`
	Visibility   DocVisibility      `json:"visibility"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListDocumentsForUser(ctx context.Context, uploadedBy pgtype.UUID) ([]ListDocumentsForUserRow, error) {
	rows, err := q.db.Query(ctx, listDocumentsForUser, uploadedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentsForUserRow{}
	for rows.Next() {
		var i ListDocumentsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UploadedBy,
			&i.GroupID,
			&i.Filename,
			&i.StoragePath,
			&i.Visibility,
			&i.PasswordHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeDocumentAccess = `-- name: RevokeDocumentAccess :exec
DELETE FROM document_access WHERE document_id = $1 AND user_id = $2
`

type RevokeDocumentAccessParams struct {
	DocumentID pgtype.UUID `json:"document_id"`
	UserID     pgtype.UUID `json:"user_id"`
}

func (q *Queries) RevokeDocumentAccess(ctx context.Context, arg RevokeDocumentAccessParams) error {
	_, err := q.db.Exec(ctx, revokeDocumentAccess, arg.DocumentID, arg.UserID)
	return err
}

const setDocumentPassword = `-- name: SetDocumentPassword :exec
UPDATE documents SET password_hash = $2 WHERE id = $1
`

type SetDocumentPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) SetDocumentPassword(ctx context.Context, arg SetDocumentPasswordParams) error {
	_, err := q.db.Exec(ctx, setDocumentPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateDocumentVisibility = `-- name: UpdateDocumentVisibility :one
UPDATE documents SET visibility = $2
WHERE id = $1
RETURNING id, uploaded_by, group_id, filename, storage_path, visibility, password_hash, created_at
`

type UpdateDocumentVisibilityParams struct {
	ID         pgtype.UUID   `json:"id"`
	Visibility DocVisibility `json:"visibility"`
}

type UpdateDocumentVisibilityRow struct {
	ID           pgtype.UUID        `json:"id"`
	UploadedBy   pgtype.UUID        `json:"uploaded_by"`
	GroupID      pgtype.UUID        `json:"group_id"`
	Filename     string             `json:"filename"`
	StoragePath  string             `json:"storage_path"`
	Visibility   DocVisibility      `json:"visibility"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateDocumentVisibility(ctx context.Context, arg UpdateDocumentVisibilityParams) (UpdateDocumentVisibilityRow, error) {
	row := q.db.QueryRow(ctx, updateDocumentVisibility, arg.ID, arg.Visibility)
	var i UpdateDocumentVisibilityRow
	err := row.Scan(
		&i.ID,
		&i.UploadedBy,
		&i.GroupID,
		&i.Filename,
		&i.StoragePath,
		&i.Visibility,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}
