// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGroupMember = `-- name: AddGroupMember :one
INSERT INTO group_members (group_id, user_id, role_in_group)
VALUES ($1, $2, $3)
RETURNING id, group_id, user_id, role_in_group, joined_at
`

type AddGroupMemberParams struct {
	GroupID     pgtype.UUID     `json:"group_id"`
	UserID      pgtype.UUID     `json:"user_id"`
	RoleInGroup GroupMemberRole `json:"role_in_group"`
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, addGroupMember, arg.GroupID, arg.UserID, arg.RoleInGroup)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.RoleInGroup,
		&i.JoinedAt,
	)
	return i, err
}

const countGroupsByOrg = `-- name: CountGroupsByOrg :one
SELECT COUNT(*) FROM groups WHERE org_id = $1
`

func (q *Queries) CountGroupsByOrg(ctx context.Context, orgID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupsByOrg, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name, type, created_by, org_id)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, name, type, created_by, created_at
`

type CreateGroupParams struct {
	Name      string      `json:"name"`
	Type      GroupType   `json:"type"`
	CreatedBy pgtype.UUID `json:"created_by"`
	OrgID     pgtype.UUID `json:"org_id"`
}

type CreateGroupRow struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Name      string             `json:"name"`
	Type      GroupType          `json:"type"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (CreateGroupRow, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.Name,
		arg.Type,
		arg.CreatedBy,
		arg.OrgID,
	)
	var i CreateGroupRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getGroup = `-- name: GetGroup :one
SELECT g.id, g.org_id, g.name, g.type, g.created_by, g.created_at
FROM groups g
WHERE g.id = $1 AND g.org_id = $2
LIMIT 1
`

type GetGroupParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

type GetGroupRow struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Name      string             `json:"name"`
	Type      GroupType          `json:"type"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetGroup(ctx context.Context, arg GetGroupParams) (GetGroupRow, error) {
	row := q.db.QueryRow(ctx, getGroup, arg.ID, arg.OrgID)
	var i GetGroupRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, org_id, name, type, created_by, created_at
FROM groups g
WHERE g.id = $1
LIMIT 1
`

type GetGroupByIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Name      string             `json:"name"`
	Type      GroupType          `json:"type"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetGroupByID(ctx context.Context, id pgtype.UUID) (GetGroupByIDRow, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i GetGroupByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupMember = `-- name: GetGroupMember :one
SELECT id, group_id, user_id, role_in_group, joined_at
FROM group_members
WHERE group_id = $1 AND user_id = $2
LIMIT 1
`

type GetGroupMemberParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetGroupMember(ctx context.Context, arg GetGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, getGroupMember, arg.GroupID, arg.UserID)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.RoleInGroup,
		&i.JoinedAt,
	)
	return i, err
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT gm.id, gm.group_id, gm.user_id, gm.role_in_group, gm.joined_at,
       u.name AS user_name, u.email, u.phone
FROM group_members gm
JOIN users u ON u.id = gm.user_id
WHERE gm.group_id = $1
ORDER BY gm.joined_at
`

type ListGroupMembersRow struct {
	ID          pgtype.UUID        `json:"id"`
	GroupID     pgtype.UUID        `json:"group_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	RoleInGroup GroupMemberRole    `json:"role_in_group"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
	UserName    string             `json:"user_name"`
	Email       pgtype.Text        `json:"email"`
	Phone       pgtype.Text        `json:"phone"`
}

func (q *Queries) ListGroupMembers(ctx context.Context, groupID pgtype.UUID) ([]ListGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupMembersRow{}
	for rows.Next() {
		var i ListGroupMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.RoleInGroup,
			&i.JoinedAt,
			&i.UserName,
			&i.Email,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsByOrg = `-- name: ListGroupsByOrg :many
SELECT id, org_id, name, type, created_by, created_at
FROM groups
WHERE ($1::uuid IS NULL OR org_id = $1)
ORDER BY created_at DESC
`

type ListGroupsByOrgRow struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Name      string             `json:"name"`
	Type      GroupType          `json:"type"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListGroupsByOrg(ctx context.Context, dollar_1 pgtype.UUID) ([]ListGroupsByOrgRow, error) {
	rows, err := q.db.Query(ctx, listGroupsByOrg, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupsByOrgRow{}
	for rows.Next() {
		var i ListGroupsByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Type,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsForUser = `-- name: ListGroupsForUser :many
SELECT g.id, g.org_id, g.name, g.type, g.created_by, g.created_at,
       gm.role_in_group
FROM groups g
JOIN group_members gm ON gm.group_id = g.id
WHERE gm.user_id = $1
ORDER BY g.created_at DESC
`

type ListGroupsForUserRow struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Name        string             `json:"name"`
	Type        GroupType          `json:"type"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	RoleInGroup GroupMemberRole    `json:"role_in_group"`
}

func (q *Queries) ListGroupsForUser(ctx context.Context, userID pgtype.UUID) ([]ListGroupsForUserRow, error) {
	rows, err := q.db.Query(ctx, listGroupsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupsForUserRow{}
	for rows.Next() {
		var i ListGroupsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Type,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.RoleInGroup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroupMember = `-- name: RemoveGroupMember :exec
DELETE FROM group_members WHERE group_id = $1 AND user_id = $2
`

type RemoveGroupMemberParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error {
	_, err := q.db.Exec(ctx, removeGroupMember, arg.GroupID, arg.UserID)
	return err
}

const searchGroupsByOrg = `-- name: SearchGroupsByOrg :many
SELECT id, org_id, name, type, created_by, created_at
FROM groups
WHERE ($1::uuid IS NULL OR org_id = $1)
  AND ($2::uuid IS NULL OR EXISTS (
        SELECT 1 FROM group_members gm WHERE gm.group_id = id AND gm.user_id = $2))
  AND name_search @@ plainto_tsquery('english', $3)
ORDER BY created_at DESC
LIMIT $4
`

type SearchGroupsByOrgParams struct {
	Column1        pgtype.UUID `json:"column_1"`
	Column2        pgtype.UUID `json:"column_2"`
	PlaintoTsquery string      `json:"plainto_tsquery"`
	Limit          int32       `json:"limit"`
}

type SearchGroupsByOrgRow struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Name      string             `json:"name"`
	Type      GroupType          `json:"type"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) SearchGroupsByOrg(ctx context.Context, arg SearchGroupsByOrgParams) ([]SearchGroupsByOrgRow, error) {
	rows, err := q.db.Query(ctx, searchGroupsByOrg,
		arg.Column1,
		arg.Column2,
		arg.PlaintoTsquery,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchGroupsByOrgRow{}
	for rows.Next() {
		var i SearchGroupsByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Type,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemberRole = `-- name: UpdateMemberRole :one
UPDATE group_members
SET role_in_group = $3
WHERE group_id = $1 AND user_id = $2
RETURNING id, group_id, user_id, role_in_group, joined_at
`

type UpdateMemberRoleParams struct {
	GroupID     pgtype.UUID     `json:"group_id"`
	UserID      pgtype.UUID     `json:"user_id"`
	RoleInGroup GroupMemberRole `json:"role_in_group"`
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, updateMemberRole, arg.GroupID, arg.UserID, arg.RoleInGroup)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.RoleInGroup,
		&i.JoinedAt,
	)
	return i, err
}
