// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (group_id, sender_id, receiver_id, content, reply_to_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, group_id, sender_id, receiver_id, content, reply_to_id, created_at, edited_at
`

type CreateMessageParams struct {
	GroupID    pgtype.UUID `json:"group_id"`
	SenderID   pgtype.UUID `json:"sender_id"`
	ReceiverID pgtype.UUID `json:"receiver_id"`
	Content    string      `json:"content"`
	ReplyToID  pgtype.UUID `json:"reply_to_id"`
}

type CreateMessageRow struct {
	ID         pgtype.UUID        `json:"id"`
	GroupID    pgtype.UUID        `json:"group_id"`
	SenderID   pgtype.UUID        `json:"sender_id"`
	ReceiverID pgtype.UUID        `json:"receiver_id"`
	Content    string             `json:"content"`
	ReplyToID  pgtype.UUID        `json:"reply_to_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	EditedAt   pgtype.Timestamptz `json:"edited_at"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (CreateMessageRow, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.GroupID,
		arg.SenderID,
		arg.ReceiverID,
		arg.Content,
		arg.ReplyToID,
	)
	var i CreateMessageRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Content,
		&i.ReplyToID,
		&i.CreatedAt,
		&i.EditedAt,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages WHERE id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessage, id)
	return err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, group_id, sender_id, receiver_id, content, reply_to_id, created_at, edited_at
FROM messages WHERE id = $1 LIMIT 1
`

type GetMessageByIDRow struct {
	ID         pgtype.UUID        `json:"id"`
	GroupID    pgtype.UUID        `json:"group_id"`
	SenderID   pgtype.UUID        `json:"sender_id"`
	ReceiverID pgtype.UUID        `json:"receiver_id"`
	Content    string             `json:"content"`
	ReplyToID  pgtype.UUID        `json:"reply_to_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	EditedAt   pgtype.Timestamptz `json:"edited_at"`
}

func (q *Queries) GetMessageByID(ctx context.Context, id pgtype.UUID) (GetMessageByIDRow, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i GetMessageByIDRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Content,
		&i.ReplyToID,
		&i.CreatedAt,
		&i.EditedAt,
	)
	return i, err
}

const listDirectMessages = `-- name: ListDirectMessages :many
SELECT id, group_id, sender_id, receiver_id, content, reply_to_id, created_at, edited_at
FROM messages
WHERE group_id IS NULL
  AND ((sender_id = $1 AND receiver_id = $2) OR (sender_id = $2 AND receiver_id = $1))
ORDER BY created_at DESC
LIMIT $3
`

type ListDirectMessagesParams struct {
	SenderID   pgtype.UUID `json:"sender_id"`
	ReceiverID pgtype.UUID `json:"receiver_id"`
	Limit      int32       `json:"limit"`
}

type ListDirectMessagesRow struct {
	ID         pgtype.UUID        `json:"id"`
	GroupID    pgtype.UUID        `json:"group_id"`
	SenderID   pgtype.UUID        `json:"sender_id"`
	ReceiverID pgtype.UUID        `json:"receiver_id"`
	Content    string             `json:"content"`
	ReplyToID  pgtype.UUID        `json:"reply_to_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	EditedAt   pgtype.Timestamptz `json:"edited_at"`
}

func (q *Queries) ListDirectMessages(ctx context.Context, arg ListDirectMessagesParams) ([]ListDirectMessagesRow, error) {
	rows, err := q.db.Query(ctx, listDirectMessages, arg.SenderID, arg.ReceiverID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDirectMessagesRow{}
	for rows.Next() {
		var i ListDirectMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.SenderID,
			&i.ReceiverID,
			&i.Content,
			&i.ReplyToID,
			&i.CreatedAt,
			&i.EditedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMessages = `-- name: ListGroupMessages :many
SELECT m.id, m.group_id, m.sender_id, m.receiver_id, m.content, m.reply_to_id, m.created_at, m.edited_at,
       COALESCE(u.display_name, u.name) AS sender_name,
       u.avatar_url AS sender_avatar,
       u.role AS sender_role,
       rm.content AS reply_content,
       COALESCE(ru.display_name, ru.name) AS reply_sender_name
FROM messages m
JOIN users u ON u.id = m.sender_id
LEFT JOIN messages rm ON rm.id = m.reply_to_id
LEFT JOIN users ru ON ru.id = rm.sender_id
WHERE m.group_id = $1
  AND ($2::timestamptz IS NULL OR m.created_at < $2)
ORDER BY m.created_at DESC
LIMIT $3
`

type ListGroupMessagesParams struct {
	GroupID pgtype.UUID        `json:"group_id"`
	Column2 pgtype.Timestamptz `json:"column_2"`
	Limit   int32              `json:"limit"`
}

type ListGroupMessagesRow struct {
	ID              pgtype.UUID        `json:"id"`
	GroupID         pgtype.UUID        `json:"group_id"`
	SenderID        pgtype.UUID        `json:"sender_id"`
	ReceiverID      pgtype.UUID        `json:"receiver_id"`
	Content         string             `json:"content"`
	ReplyToID       pgtype.UUID        `json:"reply_to_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	EditedAt        pgtype.Timestamptz `json:"edited_at"`
	SenderName      string             `json:"sender_name"`
	SenderAvatar    pgtype.Text        `json:"sender_avatar"`
	SenderRole      UserRole           `json:"sender_role"`
	ReplyContent    pgtype.Text        `json:"reply_content"`
	ReplySenderName pgtype.Text        `json:"reply_sender_name"`
}

func (q *Queries) ListGroupMessages(ctx context.Context, arg ListGroupMessagesParams) ([]ListGroupMessagesRow, error) {
	rows, err := q.db.Query(ctx, listGroupMessages, arg.GroupID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupMessagesRow{}
	for rows.Next() {
		var i ListGroupMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.SenderID,
			&i.ReceiverID,
			&i.Content,
			&i.ReplyToID,
			&i.CreatedAt,
			&i.EditedAt,
			&i.SenderName,
			&i.SenderAvatar,
			&i.SenderRole,
			&i.ReplyContent,
			&i.ReplySenderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMessagesInGroup = `-- name: SearchMessagesInGroup :many
SELECT m.id, m.group_id, m.sender_id, m.receiver_id, m.content, m.reply_to_id, m.created_at, m.edited_at,
       COALESCE(u.display_name, u.name) AS sender_name,
       u.avatar_url AS sender_avatar,
       u.role AS sender_role,
       rm.content AS reply_content,
       COALESCE(ru.display_name, ru.name) AS reply_sender_name
FROM messages m
JOIN users u ON u.id = m.sender_id
LEFT JOIN messages rm ON rm.id = m.reply_to_id
LEFT JOIN users ru ON ru.id = rm.sender_id
WHERE m.group_id = $1
  AND m.content_search @@ plainto_tsquery('english', $2)
ORDER BY m.created_at DESC
LIMIT $3
`

type SearchMessagesInGroupParams struct {
	GroupID        pgtype.UUID `json:"group_id"`
	PlaintoTsquery string      `json:"plainto_tsquery"`
	Limit          int32       `json:"limit"`
}

type SearchMessagesInGroupRow struct {
	ID              pgtype.UUID        `json:"id"`
	GroupID         pgtype.UUID        `json:"group_id"`
	SenderID        pgtype.UUID        `json:"sender_id"`
	ReceiverID      pgtype.UUID        `json:"receiver_id"`
	Content         string             `json:"content"`
	ReplyToID       pgtype.UUID        `json:"reply_to_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	EditedAt        pgtype.Timestamptz `json:"edited_at"`
	SenderName      string             `json:"sender_name"`
	SenderAvatar    pgtype.Text        `json:"sender_avatar"`
	SenderRole      UserRole           `json:"sender_role"`
	ReplyContent    pgtype.Text        `json:"reply_content"`
	ReplySenderName pgtype.Text        `json:"reply_sender_name"`
}

func (q *Queries) SearchMessagesInGroup(ctx context.Context, arg SearchMessagesInGroupParams) ([]SearchMessagesInGroupRow, error) {
	rows, err := q.db.Query(ctx, searchMessagesInGroup, arg.GroupID, arg.PlaintoTsquery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchMessagesInGroupRow{}
	for rows.Next() {
		var i SearchMessagesInGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.SenderID,
			&i.ReceiverID,
			&i.Content,
			&i.ReplyToID,
			&i.CreatedAt,
			&i.EditedAt,
			&i.SenderName,
			&i.SenderAvatar,
			&i.SenderRole,
			&i.ReplyContent,
			&i.ReplySenderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessage = `-- name: UpdateMessage :one
UPDATE messages SET content = $2, edited_at = NOW()
WHERE id = $1
RETURNING id, group_id, sender_id, receiver_id, content, reply_to_id, created_at, edited_at
`

type UpdateMessageParams struct {
	ID      pgtype.UUID `json:"id"`
	Content string      `json:"content"`
}

type UpdateMessageRow struct {
	ID        pgtype.UUID        `json:"id"`
	GroupID   pgtype.UUID        `json:"group_id"`
	SenderID  pgtype.UUID        `json:"sender_id"`
	ReceiverID pgtype.UUID       `json:"receiver_id"`
	Content   string             `json:"content"`
	ReplyToID pgtype.UUID        `json:"reply_to_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	EditedAt  pgtype.Timestamptz `json:"edited_at"`
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) (UpdateMessageRow, error) {
	row := q.db.QueryRow(ctx, updateMessage, arg.ID, arg.Content)
	var i UpdateMessageRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Content,
		&i.ReplyToID,
		&i.CreatedAt,
		&i.EditedAt,
	)
	return i, err
}
