// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type DocVisibility string

const (
	DocVisibilityAll        DocVisibility = "all"
	DocVisibilityRestricted DocVisibility = "restricted"
)

func (e *DocVisibility) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DocVisibility(s)
	case string:
		*e = DocVisibility(s)
	default:
		return fmt.Errorf("unsupported scan type for DocVisibility: %T", src)
	}
	return nil
}

type NullDocVisibility struct {
	DocVisibility DocVisibility `json:"doc_visibility"`
	Valid         bool          `json:"valid"` // Valid is true if DocVisibility is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDocVisibility) Scan(value interface{}) error {
	if value == nil {
		ns.DocVisibility, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DocVisibility.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDocVisibility) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DocVisibility), nil
}

type GroupMemberRole string

const (
	GroupMemberRoleAdmin  GroupMemberRole = "admin"
	GroupMemberRoleMember GroupMemberRole = "member"
)

func (e *GroupMemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GroupMemberRole(s)
	case string:
		*e = GroupMemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for GroupMemberRole: %T", src)
	}
	return nil
}

type NullGroupMemberRole struct {
	GroupMemberRole GroupMemberRole `json:"group_member_role"`
	Valid           bool            `json:"valid"` // Valid is true if GroupMemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGroupMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.GroupMemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GroupMemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGroupMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GroupMemberRole), nil
}

type GroupType string

const (
	GroupTypeInternal GroupType = "internal"
	GroupTypeBank     GroupType = "bank"
)

func (e *GroupType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GroupType(s)
	case string:
		*e = GroupType(s)
	default:
		return fmt.Errorf("unsupported scan type for GroupType: %T", src)
	}
	return nil
}

type NullGroupType struct {
	GroupType GroupType `json:"group_type"`
	Valid     bool      `json:"valid"` // Valid is true if GroupType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGroupType) Scan(value interface{}) error {
	if value == nil {
		ns.GroupType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GroupType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGroupType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GroupType), nil
}

type OtpChannel string

const (
	OtpChannelSms   OtpChannel = "sms"
	OtpChannelEmail OtpChannel = "email"
)

func (e *OtpChannel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OtpChannel(s)
	case string:
		*e = OtpChannel(s)
	default:
		return fmt.Errorf("unsupported scan type for OtpChannel: %T", src)
	}
	return nil
}

type NullOtpChannel struct {
	OtpChannel OtpChannel `json:"otp_channel"`
	Valid      bool       `json:"valid"` // Valid is true if OtpChannel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOtpChannel) Scan(value interface{}) error {
	if value == nil {
		ns.OtpChannel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OtpChannel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOtpChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OtpChannel), nil
}

type UserRole string

const (
	UserRoleEmployee   UserRole = "employee"
	UserRoleSuperadmin UserRole = "superadmin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Document struct {
	ID             pgtype.UUID        `json:"id"`
	UploadedBy     pgtype.UUID        `json:"uploaded_by"`
	GroupID        pgtype.UUID        `json:"group_id"`
	Filename       string             `json:"filename"`
	StoragePath    string             `json:"storage_path"`
	Visibility     DocVisibility      `json:"visibility"`
	PasswordHash   pgtype.Text        `json:"password_hash"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	FilenameSearch interface{}        `json:"filename_search"`
}

type DocumentAccess struct {
	ID         pgtype.UUID `json:"id"`
	DocumentID pgtype.UUID `json:"document_id"`
	UserID     pgtype.UUID `json:"user_id"`
}

type Group struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Type      GroupType          `json:"type"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GroupMember struct {
	ID          pgtype.UUID        `json:"id"`
	GroupID     pgtype.UUID        `json:"group_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	RoleInGroup GroupMemberRole    `json:"role_in_group"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
}

type Message struct {
	ID            pgtype.UUID        `json:"id"`
	GroupID       pgtype.UUID        `json:"group_id"`
	SenderID      pgtype.UUID        `json:"sender_id"`
	ReceiverID    pgtype.UUID        `json:"receiver_id"`
	Content       string             `json:"content"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	EditedAt      pgtype.Timestamptz `json:"edited_at"`
	ContentSearch interface{}        `json:"content_search"`
}

type OtpCode struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Code       string             `json:"code"`
	Channel    OtpChannel         `json:"channel"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Email        pgtype.Text        `json:"email"`
	Phone        pgtype.Text        `json:"phone"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	Role         UserRole           `json:"role"`
	LanguagePref string             `json:"language_pref"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	NameSearch   interface{}        `json:"name_search"`
}
