// Code generated by hand matching sqlc pattern.

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Notification struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	ActorID   pgtype.UUID        `json:"actor_id"`
	GroupID   pgtype.UUID        `json:"group_id"`
	MessageID pgtype.UUID        `json:"message_id"`
	Type      string             `json:"type"`
	IsRead    bool               `json:"is_read"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, actor_id, group_id, message_id, type)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, actor_id, group_id, message_id, type, is_read, created_at
`

type CreateNotificationParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ActorID   pgtype.UUID `json:"actor_id"`
	GroupID   pgtype.UUID `json:"group_id"`
	MessageID pgtype.UUID `json:"message_id"`
	Type      string      `json:"type"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.ActorID,
		arg.GroupID,
		arg.MessageID,
		arg.Type,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActorID,
		&i.GroupID,
		&i.MessageID,
		&i.Type,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const getUnreadCount = `-- name: GetUnreadCount :one
SELECT COUNT(*)::bigint AS unread_count
FROM notifications
WHERE user_id = $1 AND is_read = false
`

func (q *Queries) GetUnreadCount(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getUnreadCount, userID)
	var unread_count int64
	err := row.Scan(&unread_count)
	return unread_count, err
}

const listUserNotificationsByType = `-- name: ListUserNotificationsByType :many
SELECT n.id, n.user_id, n.actor_id, n.group_id, n.message_id, n.type, n.is_read, n.created_at,
       COALESCE(u.display_name, u.name) AS actor_name,
       u.avatar_url AS actor_avatar,
       g.name AS group_name,
       m.content AS message_content
FROM notifications n
JOIN users u ON u.id = n.actor_id
JOIN groups g ON g.id = n.group_id
JOIN messages m ON m.id = n.message_id
WHERE n.user_id = $1 AND (cardinality($2::text[]) = 0 OR n.type = ANY($2::text[]))
ORDER BY n.created_at DESC
LIMIT $3
`

type ListUserNotificationsByTypeParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Column2 []string   `json:"column_2"`
	Limit  int32       `json:"limit"`
}

type ListUserNotificationsByTypeRow struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	ActorID        pgtype.UUID        `json:"actor_id"`
	GroupID        pgtype.UUID        `json:"group_id"`
	MessageID      pgtype.UUID        `json:"message_id"`
	Type           string             `json:"type"`
	IsRead         bool               `json:"is_read"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ActorName      string             `json:"actor_name"`
	ActorAvatar    *string            `json:"actor_avatar"`
	GroupName      string             `json:"group_name"`
	MessageContent string             `json:"message_content"`
}

func (q *Queries) ListUserNotificationsByType(ctx context.Context, arg ListUserNotificationsByTypeParams) ([]ListUserNotificationsByTypeRow, error) {
	rows, err := q.db.Query(ctx, listUserNotificationsByType, arg.UserID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserNotificationsByTypeRow
	for rows.Next() {
		var i ListUserNotificationsByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ActorID,
			&i.GroupID,
			&i.MessageID,
			&i.Type,
			&i.IsRead,
			&i.CreatedAt,
			&i.ActorName,
			&i.ActorAvatar,
			&i.GroupName,
			&i.MessageContent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationsAsRead = `-- name: MarkNotificationsAsRead :exec
UPDATE notifications
SET is_read = true
WHERE user_id = $1 AND ($2::uuid[] IS NULL OR id = ANY($2::uuid[]))
`

type MarkNotificationsAsReadParams struct {
	UserID  pgtype.UUID   `json:"user_id"`
	Column2 []pgtype.UUID `json:"column_2"`
}

func (q *Queries) MarkNotificationsAsRead(ctx context.Context, arg MarkNotificationsAsReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationsAsRead, arg.UserID, arg.Column2)
	return err
}

const markGroupNotificationsAsRead = `-- name: MarkGroupNotificationsAsRead :exec
UPDATE notifications
SET is_read = true
WHERE user_id = $1 AND group_id = $2
`

type MarkGroupNotificationsAsReadParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	GroupID pgtype.UUID `json:"group_id"`
}

func (q *Queries) MarkGroupNotificationsAsRead(ctx context.Context, arg MarkGroupNotificationsAsReadParams) error {
	_, err := q.db.Exec(ctx, markGroupNotificationsAsRead, arg.UserID, arg.GroupID)
	return err
}
