// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orgs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, slug, staff_limit, group_limit, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, slug, is_active, staff_limit, group_limit, created_by, created_at
`

type CreateOrganizationParams struct {
	Name       string      `json:"name"`
	Slug       string      `json:"slug"`
	StaffLimit pgtype.Int4 `json:"staff_limit"`
	GroupLimit pgtype.Int4 `json:"group_limit"`
	CreatedBy  pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.Name,
		arg.Slug,
		arg.StaffLimit,
		arg.GroupLimit,
		arg.CreatedBy,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IsActive,
		&i.StaffLimit,
		&i.GroupLimit,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, name, slug, is_active, staff_limit, group_limit, created_by, created_at
FROM organizations
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetOrganization(ctx context.Context, id pgtype.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IsActive,
		&i.StaffLimit,
		&i.GroupLimit,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, is_active, staff_limit, group_limit, created_by, created_at
FROM organizations
WHERE slug = $1
LIMIT 1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IsActive,
		&i.StaffLimit,
		&i.GroupLimit,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, name, slug, is_active, staff_limit, group_limit, created_by, created_at
FROM organizations
ORDER BY created_at DESC
`

func (q *Queries) ListOrganizations(ctx context.Context) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.IsActive,
			&i.StaffLimit,
			&i.GroupLimit,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrganizationActive = `-- name: SetOrganizationActive :exec
UPDATE organizations SET is_active = $2 WHERE id = $1
`

type SetOrganizationActiveParams struct {
	ID       pgtype.UUID `json:"id"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) SetOrganizationActive(ctx context.Context, arg SetOrganizationActiveParams) error {
	_, err := q.db.Exec(ctx, setOrganizationActive, arg.ID, arg.IsActive)
	return err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
SET is_active = $2, staff_limit = $3, group_limit = $4
WHERE id = $1
RETURNING id, name, slug, is_active, staff_limit, group_limit, created_by, created_at
`

type UpdateOrganizationParams struct {
	ID         pgtype.UUID `json:"id"`
	IsActive   bool        `json:"is_active"`
	StaffLimit pgtype.Int4 `json:"staff_limit"`
	GroupLimit pgtype.Int4 `json:"group_limit"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization,
		arg.ID,
		arg.IsActive,
		arg.StaffLimit,
		arg.GroupLimit,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IsActive,
		&i.StaffLimit,
		&i.GroupLimit,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const updateOrganizationLimits = `-- name: UpdateOrganizationLimits :exec
UPDATE organizations
SET staff_limit = $2, group_limit = $3
WHERE id = $1
`

type UpdateOrganizationLimitsParams struct {
	ID         pgtype.UUID `json:"id"`
	StaffLimit pgtype.Int4 `json:"staff_limit"`
	GroupLimit pgtype.Int4 `json:"group_limit"`
}

func (q *Queries) UpdateOrganizationLimits(ctx context.Context, arg UpdateOrganizationLimitsParams) error {
	_, err := q.db.Exec(ctx, updateOrganizationLimits, arg.ID, arg.StaffLimit, arg.GroupLimit)
	return err
}
