// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddGroupMember(ctx context.Context, arg AddGroupMemberParams) (GroupMember, error)
	CountRecentOTPRequests(ctx context.Context, userID pgtype.UUID) (int64, error)
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (CreateDocumentRow, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (CreateMessageRow, error)
	CreateOTP(ctx context.Context, arg CreateOTPParams) (OtpCode, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetDocument(ctx context.Context, id pgtype.UUID) (GetDocumentRow, error)
	GetGroup(ctx context.Context, id pgtype.UUID) (Group, error)
	GetGroupMember(ctx context.Context, arg GetGroupMemberParams) (GroupMember, error)
	GetLatestValidOTP(ctx context.Context, arg GetLatestValidOTPParams) (GetLatestValidOTPRow, error)
	GetUserByEmail(ctx context.Context, email pgtype.Text) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error)
	GetUserByPhone(ctx context.Context, phone pgtype.Text) (GetUserByPhoneRow, error)
	GlobalSearchDocuments(ctx context.Context, arg GlobalSearchDocumentsParams) ([]GlobalSearchDocumentsRow, error)
	GlobalSearchMessages(ctx context.Context, arg GlobalSearchMessagesParams) ([]GlobalSearchMessagesRow, error)
	GlobalSearchUsers(ctx context.Context, plaintoTsquery string) ([]GlobalSearchUsersRow, error)
	GrantDocumentAccess(ctx context.Context, arg GrantDocumentAccessParams) error
	HasDocumentAccess(ctx context.Context, arg HasDocumentAccessParams) (bool, error)
	ListDirectMessages(ctx context.Context, arg ListDirectMessagesParams) ([]ListDirectMessagesRow, error)
	ListDocumentsForUser(ctx context.Context, uploadedBy pgtype.UUID) ([]ListDocumentsForUserRow, error)
	ListGroupMembers(ctx context.Context, groupID pgtype.UUID) ([]ListGroupMembersRow, error)
	ListGroupMessages(ctx context.Context, arg ListGroupMessagesParams) ([]ListGroupMessagesRow, error)
	ListGroupsForUser(ctx context.Context, userID pgtype.UUID) ([]ListGroupsForUserRow, error)
	MarkOTPVerified(ctx context.Context, id pgtype.UUID) error
	RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error
	RevokeDocumentAccess(ctx context.Context, arg RevokeDocumentAccessParams) error
	SearchMessagesInGroup(ctx context.Context, arg SearchMessagesInGroupParams) ([]SearchMessagesInGroupRow, error)
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error)
	SetDocumentPassword(ctx context.Context, arg SetDocumentPasswordParams) error
	UpdateDocumentVisibility(ctx context.Context, arg UpdateDocumentVisibilityParams) (UpdateDocumentVisibilityRow, error)
	UpdateLanguagePref(ctx context.Context, arg UpdateLanguagePrefParams) error
	UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (GroupMember, error)
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) (UpdateMessageRow, error)
}

var _ Querier = (*Queries)(nil)
