// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddGroupMember(ctx context.Context, arg AddGroupMemberParams) (GroupMember, error)
	ClearUserAvatar(ctx context.Context, id pgtype.UUID) (ClearUserAvatarRow, error)
	CountActiveOrgAdmins(ctx context.Context, orgID pgtype.UUID) (int64, error)
	CountGroupsByOrg(ctx context.Context, orgID pgtype.UUID) (int64, error)
	CountRecentOTPRequests(ctx context.Context, arg CountRecentOTPRequestsParams) (int64, error)
	CountUsersByOrg(ctx context.Context, orgID pgtype.UUID) (int64, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (CreateDocumentRow, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (CreateGroupRow, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (CreateMessageRow, error)
	CreateOTP(ctx context.Context, arg CreateOTPParams) (OtpCode, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeactivateUser(ctx context.Context, id pgtype.UUID) (DeactivateUserRow, error)
	GetActiveSession(ctx context.Context, tokenHash string) (Session, error)
	GetDocument(ctx context.Context, id pgtype.UUID) (GetDocumentRow, error)
	GetGroup(ctx context.Context, arg GetGroupParams) (GetGroupRow, error)
	GetGroupByID(ctx context.Context, id pgtype.UUID) (GetGroupByIDRow, error)
	GetGroupMember(ctx context.Context, arg GetGroupMemberParams) (GroupMember, error)
	GetLatestValidOTP(ctx context.Context, arg GetLatestValidOTPParams) (OtpCode, error)
	GetOrganization(ctx context.Context, id pgtype.UUID) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	GetUserAuthByContact(ctx context.Context, email pgtype.Text) (GetUserAuthByContactRow, error)
	GetUserAuthByEmail(ctx context.Context, email pgtype.Text) (GetUserAuthByEmailRow, error)
	GetUserAuthByID(ctx context.Context, id pgtype.UUID) (GetUserAuthByIDRow, error)
	GetUserAuthByPhone(ctx context.Context, phone pgtype.Text) (GetUserAuthByPhoneRow, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error)
	GlobalSearchDocuments(ctx context.Context, arg GlobalSearchDocumentsParams) ([]GlobalSearchDocumentsRow, error)
	GlobalSearchMessages(ctx context.Context, arg GlobalSearchMessagesParams) ([]GlobalSearchMessagesRow, error)
	GlobalSearchUsers(ctx context.Context, arg GlobalSearchUsersParams) ([]GlobalSearchUsersRow, error)
	GrantDocumentAccess(ctx context.Context, arg GrantDocumentAccessParams) error
	HasDocumentAccess(ctx context.Context, arg HasDocumentAccessParams) (bool, error)
	IncrementOTPAttempts(ctx context.Context, id pgtype.UUID) error
	IsEmailTaken(ctx context.Context, email pgtype.Text) (bool, error)
	IsPhoneTaken(ctx context.Context, phone pgtype.Text) (bool, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListDirectMessages(ctx context.Context, arg ListDirectMessagesParams) ([]ListDirectMessagesRow, error)
	ListDocumentsForUser(ctx context.Context, uploadedBy pgtype.UUID) ([]ListDocumentsForUserRow, error)
	ListGroupMembers(ctx context.Context, groupID pgtype.UUID) ([]ListGroupMembersRow, error)
	ListGroupMessages(ctx context.Context, arg ListGroupMessagesParams) ([]ListGroupMessagesRow, error)
	ListGroupsByOrg(ctx context.Context, dollar_1 pgtype.UUID) ([]ListGroupsByOrgRow, error)
	ListGroupsForUser(ctx context.Context, userID pgtype.UUID) ([]ListGroupsForUserRow, error)
	ListOrganizations(ctx context.Context) ([]Organization, error)
	ListUsersByOrg(ctx context.Context, arg ListUsersByOrgParams) ([]ListUsersByOrgRow, error)
	MarkOTPVerified(ctx context.Context, id pgtype.UUID) error
	RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error
	RevokeAllUserSessions(ctx context.Context, userID pgtype.UUID) error
	RevokeDocumentAccess(ctx context.Context, arg RevokeDocumentAccessParams) error
	RevokeOtherSessions(ctx context.Context, arg RevokeOtherSessionsParams) error
	RevokeSession(ctx context.Context, tokenHash string) error
	SearchGroupsByOrg(ctx context.Context, arg SearchGroupsByOrgParams) ([]SearchGroupsByOrgRow, error)
	SearchMessagesInGroup(ctx context.Context, arg SearchMessagesInGroupParams) ([]SearchMessagesInGroupRow, error)
	SearchUsersByOrg(ctx context.Context, arg SearchUsersByOrgParams) ([]SearchUsersByOrgRow, error)
	SetDocumentPassword(ctx context.Context, arg SetDocumentPasswordParams) error
	SetOrganizationActive(ctx context.Context, arg SetOrganizationActiveParams) error
	UpdateDocumentVisibility(ctx context.Context, arg UpdateDocumentVisibilityParams) (UpdateDocumentVisibilityRow, error)
	UpdateLanguagePref(ctx context.Context, arg UpdateLanguagePrefParams) error
	UpdateLastLogin(ctx context.Context, id pgtype.UUID) error
	UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (GroupMember, error)
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) (UpdateMessageRow, error)
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error)
	UpdateOrganizationLimits(ctx context.Context, arg UpdateOrganizationLimitsParams) error
	UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error
	UpdatePasswordRequireReset(ctx context.Context, arg UpdatePasswordRequireResetParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
	UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) (UpdateUserAvatarRow, error)
	UpdateUserPhone(ctx context.Context, arg UpdateUserPhoneParams) (UpdateUserPhoneRow, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error)
}

var _ Querier = (*Queries)(nil)
