// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const globalSearchDocuments = `-- name: GlobalSearchDocuments :many
SELECT id, uploaded_by, group_id, filename, storage_path, visibility, created_at
FROM documents
WHERE filename_search @@ plainto_tsquery('english', $1)
ORDER BY created_at DESC
LIMIT $2
`

type GlobalSearchDocumentsParams struct {
	PlaintoTsquery string `json:"plainto_tsquery"`
	Limit          int32  `json:"limit"`
}

type GlobalSearchDocumentsRow struct {
	ID          pgtype.UUID        `json:"id"`
	UploadedBy  pgtype.UUID        `json:"uploaded_by"`
	GroupID     pgtype.UUID        `json:"group_id"`
	Filename    string             `json:"filename"`
	StoragePath string             `json:"storage_path"`
	Visibility  DocVisibility      `json:"visibility"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GlobalSearchDocuments(ctx context.Context, arg GlobalSearchDocumentsParams) ([]GlobalSearchDocumentsRow, error) {
	rows, err := q.db.Query(ctx, globalSearchDocuments, arg.PlaintoTsquery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GlobalSearchDocumentsRow{}
	for rows.Next() {
		var i GlobalSearchDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UploadedBy,
			&i.GroupID,
			&i.Filename,
			&i.StoragePath,
			&i.Visibility,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const globalSearchMessages = `-- name: GlobalSearchMessages :many
SELECT id, group_id, sender_id, receiver_id, content, created_at, edited_at
FROM messages
WHERE content_search @@ plainto_tsquery('english', $1)
ORDER BY created_at DESC
LIMIT $2
`

type GlobalSearchMessagesParams struct {
	PlaintoTsquery string `json:"plainto_tsquery"`
	Limit          int32  `json:"limit"`
}

type GlobalSearchMessagesRow struct {
	ID         pgtype.UUID        `json:"id"`
	GroupID    pgtype.UUID        `json:"group_id"`
	SenderID   pgtype.UUID        `json:"sender_id"`
	ReceiverID pgtype.UUID        `json:"receiver_id"`
	Content    string             `json:"content"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	EditedAt   pgtype.Timestamptz `json:"edited_at"`
}

func (q *Queries) GlobalSearchMessages(ctx context.Context, arg GlobalSearchMessagesParams) ([]GlobalSearchMessagesRow, error) {
	rows, err := q.db.Query(ctx, globalSearchMessages, arg.PlaintoTsquery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GlobalSearchMessagesRow{}
	for rows.Next() {
		var i GlobalSearchMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.SenderID,
			&i.ReceiverID,
			&i.Content,
			&i.CreatedAt,
			&i.EditedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const globalSearchUsers = `-- name: GlobalSearchUsers :many
SELECT id, name, email, phone, role, language_pref, created_at
FROM users
WHERE name_search @@ plainto_tsquery('english', $1)
ORDER BY created_at DESC
`

type GlobalSearchUsersRow struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Email        pgtype.Text        `json:"email"`
	Phone        pgtype.Text        `json:"phone"`
	Role         UserRole           `json:"role"`
	LanguagePref string             `json:"language_pref"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GlobalSearchUsers(ctx context.Context, plaintoTsquery string) ([]GlobalSearchUsersRow, error) {
	rows, err := q.db.Query(ctx, globalSearchUsers, plaintoTsquery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GlobalSearchUsersRow{}
	for rows.Next() {
		var i GlobalSearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Role,
			&i.LanguagePref,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
