// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const globalSearchDocuments = `-- name: GlobalSearchDocuments :many
SELECT d.id, d.uploaded_by, d.group_id, d.filename, d.storage_path, d.visibility, d.created_at
FROM documents d
LEFT JOIN groups g ON g.id = d.group_id
WHERE ($1::uuid IS NULL OR g.org_id = $1)
  AND ($2::uuid IS NULL
       OR d.uploaded_by = $2
       OR EXISTS (
        SELECT 1 FROM group_members gm WHERE gm.group_id = d.group_id AND gm.user_id = $2))
  AND d.filename_search @@ plainto_tsquery('english', $3)
ORDER BY d.created_at DESC
LIMIT $4
`

type GlobalSearchDocumentsParams struct {
	Column1        pgtype.UUID `json:"column_1"`
	Column2        pgtype.UUID `json:"column_2"`
	PlaintoTsquery string      `json:"plainto_tsquery"`
	Limit          int32       `json:"limit"`
}

type GlobalSearchDocumentsRow struct {
	ID          pgtype.UUID        `json:"id"`
	UploadedBy  pgtype.UUID        `json:"uploaded_by"`
	GroupID     pgtype.UUID        `json:"group_id"`
	Filename    string             `json:"filename"`
	StoragePath string             `json:"storage_path"`
	Visibility  DocVisibility      `json:"visibility"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GlobalSearchDocuments(ctx context.Context, arg GlobalSearchDocumentsParams) ([]GlobalSearchDocumentsRow, error) {
	rows, err := q.db.Query(ctx, globalSearchDocuments,
		arg.Column1,
		arg.Column2,
		arg.PlaintoTsquery,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GlobalSearchDocumentsRow{}
	for rows.Next() {
		var i GlobalSearchDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UploadedBy,
			&i.GroupID,
			&i.Filename,
			&i.StoragePath,
			&i.Visibility,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const globalSearchMessages = `-- name: GlobalSearchMessages :many
SELECT m.id, m.group_id, m.sender_id, m.receiver_id, m.content, m.created_at, m.edited_at
FROM messages m
JOIN groups g ON g.id = m.group_id
WHERE ($1::uuid IS NULL OR g.org_id = $1)
  AND ($2::uuid IS NULL OR EXISTS (
        SELECT 1 FROM group_members gm WHERE gm.group_id = g.id AND gm.user_id = $2))
  AND m.content_search @@ plainto_tsquery('english', $3)
ORDER BY m.created_at DESC
LIMIT $4
`

type GlobalSearchMessagesParams struct {
	Column1        pgtype.UUID `json:"column_1"`
	Column2        pgtype.UUID `json:"column_2"`
	PlaintoTsquery string      `json:"plainto_tsquery"`
	Limit          int32       `json:"limit"`
}

type GlobalSearchMessagesRow struct {
	ID         pgtype.UUID        `json:"id"`
	GroupID    pgtype.UUID        `json:"group_id"`
	SenderID   pgtype.UUID        `json:"sender_id"`
	ReceiverID pgtype.UUID        `json:"receiver_id"`
	Content    string             `json:"content"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	EditedAt   pgtype.Timestamptz `json:"edited_at"`
}

func (q *Queries) GlobalSearchMessages(ctx context.Context, arg GlobalSearchMessagesParams) ([]GlobalSearchMessagesRow, error) {
	rows, err := q.db.Query(ctx, globalSearchMessages,
		arg.Column1,
		arg.Column2,
		arg.PlaintoTsquery,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GlobalSearchMessagesRow{}
	for rows.Next() {
		var i GlobalSearchMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.SenderID,
			&i.ReceiverID,
			&i.Content,
			&i.CreatedAt,
			&i.EditedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const globalSearchUsers = `-- name: GlobalSearchUsers :many
SELECT id, org_id, name, email, phone, role, language_pref, is_active, last_login_at, created_at
FROM users
WHERE ($1::uuid IS NULL OR org_id = $1)
  AND name_search @@ plainto_tsquery('english', $2)
ORDER BY created_at DESC
`

type GlobalSearchUsersParams struct {
	Column1        pgtype.UUID `json:"column_1"`
	PlaintoTsquery string      `json:"plainto_tsquery"`
}

type GlobalSearchUsersRow struct {
	ID           pgtype.UUID        `json:"id"`
	OrgID        pgtype.UUID        `json:"org_id"`
	Name         string             `json:"name"`
	Email        pgtype.Text        `json:"email"`
	Phone        pgtype.Text        `json:"phone"`
	Role         UserRole           `json:"role"`
	LanguagePref string             `json:"language_pref"`
	IsActive     bool               `json:"is_active"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GlobalSearchUsers(ctx context.Context, arg GlobalSearchUsersParams) ([]GlobalSearchUsersRow, error) {
	rows, err := q.db.Query(ctx, globalSearchUsers, arg.Column1, arg.PlaintoTsquery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GlobalSearchUsersRow{}
	for rows.Next() {
		var i GlobalSearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Role,
			&i.LanguagePref,
			&i.IsActive,
			&i.LastLoginAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
