// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearUserAvatar = `-- name: ClearUserAvatar :one
UPDATE users SET avatar_url = NULL
WHERE id = $1
RETURNING id, org_id, name, display_name, email, phone, avatar_url, role, language_pref, is_active, invited_by, must_change_password, last_login_at, created_at
`

type ClearUserAvatarRow struct {
	ID                 pgtype.UUID        `json:"id"`
	OrgID              pgtype.UUID        `json:"org_id"`
	Name               string             `json:"name"`
	DisplayName        pgtype.Text        `json:"display_name"`
	Email              pgtype.Text        `json:"email"`
	Phone              pgtype.Text        `json:"phone"`
	AvatarUrl          pgtype.Text        `json:"avatar_url"`
	Role               UserRole           `json:"role"`
	LanguagePref       string             `json:"language_pref"`
	IsActive           bool               `json:"is_active"`
	InvitedBy          pgtype.UUID        `json:"invited_by"`
	MustChangePassword bool               `json:"must_change_password"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ClearUserAvatar(ctx context.Context, id pgtype.UUID) (ClearUserAvatarRow, error) {
	row := q.db.QueryRow(ctx, clearUserAvatar, id)
	var i ClearUserAvatarRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.AvatarUrl,
		&i.Role,
		&i.LanguagePref,
		&i.IsActive,
		&i.InvitedBy,
		&i.MustChangePassword,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const countActiveOrgAdmins = `-- name: CountActiveOrgAdmins :one
SELECT COUNT(*) FROM users WHERE org_id = $1 AND role = 'org_admin' AND is_active = TRUE
`

func (q *Queries) CountActiveOrgAdmins(ctx context.Context, orgID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveOrgAdmins, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByOrg = `-- name: CountUsersByOrg :one
SELECT COUNT(*) FROM users WHERE org_id = $1
`

func (q *Queries) CountUsersByOrg(ctx context.Context, orgID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByOrg, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deactivateUser = `-- name: DeactivateUser :one
UPDATE users SET is_active = FALSE
WHERE id = $1
RETURNING id, org_id, name, display_name, email, phone, avatar_url, role, language_pref, is_active, invited_by, must_change_password, last_login_at, created_at
`

type DeactivateUserRow struct {
	ID                 pgtype.UUID        `json:"id"`
	OrgID              pgtype.UUID        `json:"org_id"`
	Name               string             `json:"name"`
	DisplayName        pgtype.Text        `json:"display_name"`
	Email              pgtype.Text        `json:"email"`
	Phone              pgtype.Text        `json:"phone"`
	AvatarUrl          pgtype.Text        `json:"avatar_url"`
	Role               UserRole           `json:"role"`
	LanguagePref       string             `json:"language_pref"`
	IsActive           bool               `json:"is_active"`
	InvitedBy          pgtype.UUID        `json:"invited_by"`
	MustChangePassword bool               `json:"must_change_password"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) DeactivateUser(ctx context.Context, id pgtype.UUID) (DeactivateUserRow, error) {
	row := q.db.QueryRow(ctx, deactivateUser, id)
	var i DeactivateUserRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.AvatarUrl,
		&i.Role,
		&i.LanguagePref,
		&i.IsActive,
		&i.InvitedBy,
		&i.MustChangePassword,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, org_id, name, display_name, email, phone, avatar_url, role, language_pref, is_active, invited_by, must_change_password, last_login_at, created_at
FROM users
WHERE id = $1
LIMIT 1
`

type GetUserByIDRow struct {
	ID                 pgtype.UUID        `json:"id"`
	OrgID              pgtype.UUID        `json:"org_id"`
	Name               string             `json:"name"`
	DisplayName        pgtype.Text        `json:"display_name"`
	Email              pgtype.Text        `json:"email"`
	Phone              pgtype.Text        `json:"phone"`
	AvatarUrl          pgtype.Text        `json:"avatar_url"`
	Role               UserRole           `json:"role"`
	LanguagePref       string             `json:"language_pref"`
	IsActive           bool               `json:"is_active"`
	InvitedBy          pgtype.UUID        `json:"invited_by"`
	MustChangePassword bool               `json:"must_change_password"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.AvatarUrl,
		&i.Role,
		&i.LanguagePref,
		&i.IsActive,
		&i.InvitedBy,
		&i.MustChangePassword,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const listUsersByOrg = `-- name: ListUsersByOrg :many
SELECT id, org_id, name, display_name, email, phone, avatar_url, role, language_pref, is_active, invited_by, must_change_password, last_login_at, created_at
FROM users
WHERE ($1::uuid IS NULL OR org_id = $1)
ORDER BY created_at DESC
LIMIT $2
`

type ListUsersByOrgParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Limit   int32       `json:"limit"`
}

type ListUsersByOrgRow struct {
	ID                 pgtype.UUID        `json:"id"`
	OrgID              pgtype.UUID        `json:"org_id"`
	Name               string             `json:"name"`
	DisplayName        pgtype.Text        `json:"display_name"`
	Email              pgtype.Text        `json:"email"`
	Phone              pgtype.Text        `json:"phone"`
	AvatarUrl          pgtype.Text        `json:"avatar_url"`
	Role               UserRole           `json:"role"`
	LanguagePref       string             `json:"language_pref"`
	IsActive           bool               `json:"is_active"`
	InvitedBy          pgtype.UUID        `json:"invited_by"`
	MustChangePassword bool               `json:"must_change_password"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUsersByOrg(ctx context.Context, arg ListUsersByOrgParams) ([]ListUsersByOrgRow, error) {
	rows, err := q.db.Query(ctx, listUsersByOrg, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersByOrgRow{}
	for rows.Next() {
		var i ListUsersByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.DisplayName,
			&i.Email,
			&i.Phone,
			&i.AvatarUrl,
			&i.Role,
			&i.LanguagePref,
			&i.IsActive,
			&i.InvitedBy,
			&i.MustChangePassword,
			&i.LastLoginAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersByOrg = `-- name: SearchUsersByOrg :many
SELECT id, org_id, name, display_name, email, phone, avatar_url, role, language_pref, is_active, invited_by, must_change_password, last_login_at, created_at
FROM users
WHERE ($1::uuid IS NULL OR org_id = $1)
  AND (
    name_search @@ plainto_tsquery('english', $2)
    OR name ILIKE '%' || $2 || '%'
    OR email ILIKE '%' || $2 || '%'
    OR phone ILIKE '%' || $2 || '%'
  )
ORDER BY created_at DESC
LIMIT $3
`

type SearchUsersByOrgParams struct {
	Column1        pgtype.UUID `json:"column_1"`
	PlaintoTsquery string      `json:"plainto_tsquery"`
	Limit          int32       `json:"limit"`
}

type SearchUsersByOrgRow struct {
	ID                 pgtype.UUID        `json:"id"`
	OrgID              pgtype.UUID        `json:"org_id"`
	Name               string             `json:"name"`
	DisplayName        pgtype.Text        `json:"display_name"`
	Email              pgtype.Text        `json:"email"`
	Phone              pgtype.Text        `json:"phone"`
	AvatarUrl          pgtype.Text        `json:"avatar_url"`
	Role               UserRole           `json:"role"`
	LanguagePref       string             `json:"language_pref"`
	IsActive           bool               `json:"is_active"`
	InvitedBy          pgtype.UUID        `json:"invited_by"`
	MustChangePassword bool               `json:"must_change_password"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) SearchUsersByOrg(ctx context.Context, arg SearchUsersByOrgParams) ([]SearchUsersByOrgRow, error) {
	rows, err := q.db.Query(ctx, searchUsersByOrg, arg.Column1, arg.PlaintoTsquery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersByOrgRow{}
	for rows.Next() {
		var i SearchUsersByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.DisplayName,
			&i.Email,
			&i.Phone,
			&i.AvatarUrl,
			&i.Role,
			&i.LanguagePref,
			&i.IsActive,
			&i.InvitedBy,
			&i.MustChangePassword,
			&i.LastLoginAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $3,
    email = $4,
    phone = $5,
    role = $6,
    language_pref = $7,
    is_active = $8
WHERE id = $1 AND ($2::uuid IS NULL OR org_id = $2)
RETURNING id, org_id, name, display_name, email, phone, avatar_url, role, language_pref, is_active, invited_by, must_change_password, last_login_at, created_at
`

type UpdateUserParams struct {
	ID           pgtype.UUID `json:"id"`
	Column2      pgtype.UUID `json:"column_2"`
	Name         string      `json:"name"`
	Email        pgtype.Text `json:"email"`
	Phone        pgtype.Text `json:"phone"`
	Role         UserRole    `json:"role"`
	LanguagePref string      `json:"language_pref"`
	IsActive     bool        `json:"is_active"`
}

type UpdateUserRow struct {
	ID                 pgtype.UUID        `json:"id"`
	OrgID              pgtype.UUID        `json:"org_id"`
	Name               string             `json:"name"`
	DisplayName        pgtype.Text        `json:"display_name"`
	Email              pgtype.Text        `json:"email"`
	Phone              pgtype.Text        `json:"phone"`
	AvatarUrl          pgtype.Text        `json:"avatar_url"`
	Role               UserRole           `json:"role"`
	LanguagePref       string             `json:"language_pref"`
	IsActive           bool               `json:"is_active"`
	InvitedBy          pgtype.UUID        `json:"invited_by"`
	MustChangePassword bool               `json:"must_change_password"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Column2,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Role,
		arg.LanguagePref,
		arg.IsActive,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.AvatarUrl,
		&i.Role,
		&i.LanguagePref,
		&i.IsActive,
		&i.InvitedBy,
		&i.MustChangePassword,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :one
UPDATE users SET avatar_url = $2
WHERE id = $1
RETURNING id, org_id, name, display_name, email, phone, avatar_url, role, language_pref, is_active, invited_by, must_change_password, last_login_at, created_at
`

type UpdateUserAvatarParams struct {
	ID        pgtype.UUID `json:"id"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

type UpdateUserAvatarRow struct {
	ID                 pgtype.UUID        `json:"id"`
	OrgID              pgtype.UUID        `json:"org_id"`
	Name               string             `json:"name"`
	DisplayName        pgtype.Text        `json:"display_name"`
	Email              pgtype.Text        `json:"email"`
	Phone              pgtype.Text        `json:"phone"`
	AvatarUrl          pgtype.Text        `json:"avatar_url"`
	Role               UserRole           `json:"role"`
	LanguagePref       string             `json:"language_pref"`
	IsActive           bool               `json:"is_active"`
	InvitedBy          pgtype.UUID        `json:"invited_by"`
	MustChangePassword bool               `json:"must_change_password"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) (UpdateUserAvatarRow, error) {
	row := q.db.QueryRow(ctx, updateUserAvatar, arg.ID, arg.AvatarUrl)
	var i UpdateUserAvatarRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.AvatarUrl,
		&i.Role,
		&i.LanguagePref,
		&i.IsActive,
		&i.InvitedBy,
		&i.MustChangePassword,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserPhone = `-- name: UpdateUserPhone :one
UPDATE users SET phone = $2
WHERE id = $1
RETURNING id, org_id, name, display_name, email, phone, avatar_url, role, language_pref, is_active, invited_by, must_change_password, last_login_at, created_at
`

type UpdateUserPhoneParams struct {
	ID    pgtype.UUID `json:"id"`
	Phone pgtype.Text `json:"phone"`
}

type UpdateUserPhoneRow struct {
	ID                 pgtype.UUID        `json:"id"`
	OrgID              pgtype.UUID        `json:"org_id"`
	Name               string             `json:"name"`
	DisplayName        pgtype.Text        `json:"display_name"`
	Email              pgtype.Text        `json:"email"`
	Phone              pgtype.Text        `json:"phone"`
	AvatarUrl          pgtype.Text        `json:"avatar_url"`
	Role               UserRole           `json:"role"`
	LanguagePref       string             `json:"language_pref"`
	IsActive           bool               `json:"is_active"`
	InvitedBy          pgtype.UUID        `json:"invited_by"`
	MustChangePassword bool               `json:"must_change_password"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateUserPhone(ctx context.Context, arg UpdateUserPhoneParams) (UpdateUserPhoneRow, error) {
	row := q.db.QueryRow(ctx, updateUserPhone, arg.ID, arg.Phone)
	var i UpdateUserPhoneRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.AvatarUrl,
		&i.Role,
		&i.LanguagePref,
		&i.IsActive,
		&i.InvitedBy,
		&i.MustChangePassword,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users SET display_name = $2
WHERE id = $1
RETURNING id, org_id, name, display_name, email, phone, avatar_url, role, language_pref, is_active, invited_by, must_change_password, last_login_at, created_at
`

type UpdateUserProfileParams struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName pgtype.Text `json:"display_name"`
}

type UpdateUserProfileRow struct {
	ID                 pgtype.UUID        `json:"id"`
	OrgID              pgtype.UUID        `json:"org_id"`
	Name               string             `json:"name"`
	DisplayName        pgtype.Text        `json:"display_name"`
	Email              pgtype.Text        `json:"email"`
	Phone              pgtype.Text        `json:"phone"`
	AvatarUrl          pgtype.Text        `json:"avatar_url"`
	Role               UserRole           `json:"role"`
	LanguagePref       string             `json:"language_pref"`
	IsActive           bool               `json:"is_active"`
	InvitedBy          pgtype.UUID        `json:"invited_by"`
	MustChangePassword bool               `json:"must_change_password"`
	LastLoginAt        pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.DisplayName)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.AvatarUrl,
		&i.Role,
		&i.LanguagePref,
		&i.IsActive,
		&i.InvitedBy,
		&i.MustChangePassword,
		&i.LastLoginAt,
		&i.CreatedAt,
	)
	return i, err
}
